# Generated by Django 4.0.6 on 2022-07-20 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthday', models.DateField(db_column='birthday', verbose_name='День рождения')),
                ('status', models.TextField(db_column='status', max_length=140, verbose_name='статус')),
                ('bio', models.TextField(db_column='bio', verbose_name='био')),
            ],
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, db_column='date', verbose_name='дата')),
                ('title', models.TextField(db_column='title', max_length=255, verbose_name='заголовок')),
                ('text', models.TextField(db_column='text', max_length=255, verbose_name='текст')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.users')),
            ],
        ),
    ]
